### ISSUE TITLE
Text alignment breaks with this plugin

### ISSUE THREAD

**Issue by LFalch** [NicoNekoru/obsidan-advanced-table-xt#1]
You can normally set text-alignment by placing `:` on the sides of the dashes under the header row. This does not work with this plugin on. I am assuming this could be related to issues with conflicting styles when cells are merged. Have I missed the way you're supposed to do this with this plugin or is this a bug? Either way, it would be nice if the normal syntax was supported.

**Comment by NicoNekoru** [comment]
Ah, I haven't yet pushed that change to the latest release. It should be fixed and allowed in the latest release, let me know if it still isn't working as expected.
