### ISSUE TITLE
A blank space before content

### ISSUE THREAD

**Issue by Ce1este** [NicoNekoru/obsidan-advanced-table-xt#11]
After updating to version 1.11, there's a blank space before content in each cell of the table.

![image](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/51806751/22990029-f290-447d-aa1e-c36d4ddedd1d)

Sometimes this can make the layout of the table look strange.

![image](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/51806751/ff667169-bd39-4c68-9f52-afe6cb3b58a4)

**Comment by NicoNekoru** [comment]
Ah while I fixed the flashing problem in #9 my fix broke something else...
