### ISSUE TITLE
This plugin is great, but it affects the original syntax. Display with previous documents.

### ISSUE THREAD

**Issue by zhoulonghao520** [NicoNekoru/obsidan-advanced-table-xt#12]
This plugin is very good. Before discovering it, I used asciidoctable because it supports many formats and table width settings, and it does not affect the original MARKDOWN syntax. After installing this plugin, all the tables in my original asciidoctable cannot be displayed. It would be even better if this plugin also had an unaffected MARKDOWN syntax. This way, many of my previous notes can be displayed normally.

![image](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/144794808/b5448658-dc12-477e-b49d-8cbb4a120e97)
![image](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/144794808/d26ba842-d319-4420-98be-2bcb9b95d69a)

asciidoc Original style
![image](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/144794808/9f5db59f-4c8f-4a2f-a19b-7df68f43031b)

**Comment by NicoNekoru** [comment]
Ah, that is a great idea. I will add option to enable native table postprocessing as a setting in the next update. Thank you for the suggestion!

**Comment by zhoulonghao520** [comment]
Thank you very much for your reply. The syntax of your plugin is very brief. If you can run it as a code block without affecting other syntax (AsciidocTable Plugin / MarkdownTable/  AnyBlockPlugin Table), it would be much more reasonable。


 am very excited to see your plugin and tried it out as soon as possible. After editing the latest notes, I found that all the old ones were formatted incorrectly, so I will discuss it with you.

**Comment by NicoNekoru** [comment]
> Thank you very much for your reply. The syntax of your plugin is very brief. If you can run it as a code block without affecting other syntax (AsciidocTable Plugin / MarkdownTable/ AnyBlockPlugin Table), it would be much more reasonable。

@zhoulonghao520 This should now be an option in the settings in the latest version (1.2.0); please let me know if there is anything else you were looking for

**Comment by zhoulonghao520** [comment]
![image](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/144794808/f9ac83f5-cf2a-4499-8eb9-4f7fd615614b)
It's perfect, I can't wait to use it to write my new document. That's great! I'm too excited.
