### ISSUE TITLE
HTML tags are not supported as code blocks

### ISSUE THREAD

**Issue by zhoulonghao520** [NicoNekoru/obsidan-advanced-table-xt#13]
![image](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/144794808/998ca02c-5504-40e0-b443-9165de07ecfd)

![image](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/144794808/eb25f312-b52c-41a4-861a-f6494f02df47)

HTML tags are not supported as code blocks

**Comment by zhoulonghao520** [comment]
![image](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/144794808/792188c5-a14d-4c99-9b88-f4b595b5f8fc)

My usual writing habit is like this, mainly used for writing software documents。

It would be even better if we could wrap it up···

**Comment by NicoNekoru** [comment]
@zhoulonghao520 HTML rendering in `sheet` lang should be resolved now 👍

**Comment by zhoulonghao520** [comment]
![image](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/144794808/59299b46-a1c1-4e28-9a22-a0e57358b3c1)


It's great, it's completely comparable to the asciidoc I used before. The disadvantage of asciidoctable is that it does not support HTML tags, such as<br/>, which is very cumbersome to handle and requires hitting the carriage return twice.



Like the picture. Too much content is very inconvenient to edit. It takes time to find the correct location for each change.

**Comment by zhoulonghao520** [comment]
![image](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/144794808/67b54c02-9fab-4c72-a5e0-661df9b8f3e9)

If the '|' symbol can wrap and render normally, it would be more convenient



for example



|Col1 | col2 | col3|

|C1-r1
|C2-r1
|C3-r1
|

|C1-r2
|C2-r2
|C3-r2
|

**Comment by zhoulonghao520** [comment]
![image](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/144794808/d6c4082c-4ad8-4d2e-80e3-265e24cfa13a)
