### ISSUE TITLE
 Table head not supported, special display

### ISSUE THREAD

**Issue by zhoulonghao520** [NicoNekoru/obsidan-advanced-table-xt#14]
<img width="1226" alt="image" src="https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/144794808/0b1a02ab-82be-4e51-b589-bfaadbc31014">

 Table head not supported, special display

**Comment by NicoNekoru** [comment]
What exactly is your problem here?

**Comment by zhoulonghao520** [comment]
<img width="846" alt="image" src="https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/144794808/8fe567b4-c8be-475e-8260-5d4efa91fc8c">

**Comment by zhoulonghao520** [comment]
There is no such problem anymore, just modify the style to achieve complex headers. Just change the second line to the same background color as the header

**Comment by zhoulonghao520** [comment]
This issue can be closed now··
