### ISSUE TITLE
 {background-color:"blue" }   blue background not displayed properly

### ISSUE THREAD

**Issue by zhoulonghao520** [NicoNekoru/obsidan-advanced-table-xt#18]
```
| Custom  | css                             | cells |
| ------- | ------------------------------- | ----- |
| foo ~ {color:"red" }  | foo ~ {background-color:"blue" } | <     |
|         |                                 |       |
```

![image](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/144794808/7119cf36-030c-4fad-83ca-ab0506e5d975)

 {background-color:"blue" }
 
 blue background not displayed properly

**Comment by NicoNekoru** [comment]
Can you try `backgroundColor` instead

**Comment by zhoulonghao520** [comment]
IsOkOkay, all the “-”  in CSS need to be removed?   
Do the following characters need to be capitalized?

**Comment by NicoNekoru** [comment]
Yes, css styles which are accessible in JS end up replacing `a-b` with `aB`. I can try to add both as valid, but for now the plugin just uses camelCase for css styles.
