### ISSUE TITLE
Set whether the plugin takes effect on the page through yaml（Advanced tables have no effect）

### ISSUE THREAD

**Issue by zhoulonghao520** [NicoNekoru/obsidan-advanced-table-xt#19]
I have used many Asciidoc tables in my past notes, and in the future, I would like to use your plugin and Advanced Tables to replace the original method. This way of writing is more concise.
Can you modify it to support using yaml to set whether this plugin is valid for the current page?
That way, I don't have to modify the original notes,
You don'tneed to use this plugin through code blocks.
Because Advanced Tables currently do not support running in code blocks.

If it could be used like this, it would be really perfect.

![image](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/144794808/20c1b722-1398-4af3-87cb-402e8d857890)

**Comment by abiriadev** [comment]
> Can you modify it to support using yaml to set whether this plugin is valid for the current page?

Do you mean supporting a (yaml)frontmatter option to disable the plugin on some pages?

**Comment by zhoulonghao520** [comment]
yes`````

**Comment by abiriadev** [comment]
@zhoulonghao520 I made a pull request for this. You can clone [this repository](https://github.com/abiriadev/obsidan-advanced-table-xt) and build it manually as a temporary workaround for now.
