### ISSUE TITLE
Error: `Malformed table` when exporting pdf

### ISSUE THREAD

**Issue by angelbanderasudg** [NicoNekoru/obsidan-advanced-table-xt#2]
If the plugin is enabled and try to export the file as pdf I get "Error: `Malformed table`", example table:
```
| Otológicos       | Nasosinusales     | Faringolaríngeos   | Cuello                         |
| ---------------- | ----------------- | ------------------ | ------------------------------ |
| Hipoacusia       | Obstrucción nasal | Disnea             | Tumor                          |
| Acúfeno          | Anosmia           | Disfonía           | Parálisis de nervios craneales |
| Otalgia          | Dolor facial      | Odinofagia         | Dolor / carotidinia            |
| Otorrea          | Rinorrea          | Expectoración      | Secreción de fistulas          |
| Otorragia        | Epistaxis         | Hemoptisis         | Hematoma /Sangrado             |
| Vértigo          | Congestión        | Disfagia / reflujo | Disnea                         |
| Parálisis facial | Estornudos        | Tos                | Disfagia /aspiración           |
```

**Comment by NicoNekoru** [comment]
Hmm... I'm not seeming to experience this behavior with the example table you provided. What other plugins do you have enabled and can you detail out the steps to reproduce this error?

**Comment by angelbanderasudg** [comment]
Hi I have try in a new vault, I am using macbook air m1
My app version: 
<img width="184" alt="image" src="https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/70727659/901cb53f-3ea4-4b6b-8487-6d55ff6f381b">
1. Create new vault
2. Activate community plugins
3. Install advanced tables plugin and activate, then deactivate (only for create plugins folder)
4. Go to plugins folder
5. Create obsidan-advanced-table-xt folder
6. Put in it main.js, manifest.json and styles.css 
7. Reload plugins in obsidian
8. Activate Sheets Extended plugin
9. Create document with table, (here it works well)
```
# Title

| Otológicos       | Nasosinusales     | Faringolaríngeos   | Cuello                         |
| ---------------- | ----------------- | ------------------ | ------------------------------ |
| Hipoacusia       | Obstrucción nasal | Disnea             | Tumor                          |
| Acúfeno          | Anosmia           | Disfonía           | Parálisis de nervios craneales |
| Otalgia          | Dolor facial      | Odinofagia         | Dolor / carotidinia            |
| Otorrea          | Rinorrea          | Expectoración      | Secreción de fistulas          |
| Otorragia        | Epistaxis         | Hemoptisis         | Hematoma /Sangrado             |
| Vértigo          | Congestión        | Disfagia / reflujo | Disnea                         |
| Parálisis facial | Estornudos        | Tos                | Disfagia /aspiración           |
```
10. Export to pdf
<img width="528" alt="image" src="https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/70727659/d6cfe9bd-b310-4470-b626-af4c9babdd0d">

Testing I see that the source variable of main.js Gets all the content of the document when exporting to pdf and this doesn't happen in live preview
<img width="533" alt="image" src="https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/70727659/3779671b-1e5e-4712-962d-8d835d222511">

**Comment by NicoNekoru** [comment]
Thanks for the steps to reproduce, as far as I can tell this seems to be an inconsistency (bug?) with Obsidian's `registerMarkdownPostProcessor` from reader mode and live preview to export to PDF. I will try to work around the issue, thanks for reporting

**Comment by NicoNekoru** [comment]
Fixed in newest release!
