### ISSUE TITLE
Wrongful "Malformed Table" Warning in Reading Mode

### ISSUE THREAD

**Issue by JackMatanky** [NicoNekoru/obsidan-advanced-table-xt#22]
Hi,
With tables inside a callout, the plugin gives the "Malformed" error message when in reading view.

Source Code:

```
> [!info] Callout
> 
> | head 1 | head 2 | head 3 |
> | ---- | ---- | ---- |
> | 1a | 2a | 3a |
> | 1b | 2b | 2c |
```

Vanilla Obsidian Result:
![image](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/98520159/0520eeb4-1e1e-4bb9-ae8b-25843266cc6c)

Result w/ "Sheet Extended" enabled:
![image](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/98520159/c586a6cc-9736-4ff6-97d5-eca9d3fe1d19)

**Comment by abiriadev** [comment]
Possibly related to #15

**Comment by JackMatanky** [comment]
Thanks, love the plugin!
