### ISSUE TITLE
Inline Buttons not working in tables

### ISSUE THREAD

**Issue by JackMatanky** [NicoNekoru/obsidan-advanced-table-xt#24]
Hi, 

I have [inline buttons](https://github.com/shabegom/buttons) placed in tables. Until today, they all worked just fine, but have stopped working. Any chance this is due to the plugin?

**Comment by NicoNekoru** [comment]
Can you provide more information about your usecase and what behaviors are not working as expected?

**Comment by JackMatanky** [comment]
Background:
The [buttons](https://github.com/shabegom/buttons) plugin has an option for embedding [inline buttons](https://github.com/shabegom/buttons#inline-buttons) by enclosing the button id in backticks. 

Use case:
In my Obsidian setup, I have a table of inline buttons in the side panel to easily create templates.
![image](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/98520159/71f93358-8aaa-49ae-8941-4c0d522fd28b)

Expected behavior:
When loading Obsidian, the side-panel table with inline buttons loads automatically and clicking on a button executes the associated command, e.g. creates a new template note as it does outside of a table.

Current behavior:
When loading Obsidian, the table does not load automatically, but requires me to remove it from the side panel, close the file, and then reopen the file to load properly and when I click on an inline button in a table, nothing happens.
![image](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/98520159/aa1b3ce1-e019-4564-a5ac-6f4a44192dc4)

**Comment by NicoNekoru** [comment]
Is this problem still present?

**Comment by JackMatanky** [comment]
Because buttons are a critical part of my workflow, unfortunately, I had to stop using the plugin
