### ISSUE TITLE
DataViewJS won't render

### ISSUE THREAD

**Issue by cklaffer** [NicoNekoru/obsidan-advanced-table-xt#26]
When I have this plugin installed with "Native table post processing" activated, dataviewjs blocks in the same or other files don't render. If I make changes in *any* file, no matter if it has a SheetsExtended table or just any other file, only then the dataviewjs blocks will render after a brief amount of time ("view refreshing" option is enabled in dataview plugin). I tried disabling all other addons, it is definitely a Sheets Extended issue.

**Comment by NicoNekoru** [comment]
I'm not experiencing exactly the same issue as you described with dataview so I'm not sure if this fix will work, but I had a problem with dataview not loading in reading mode on initial vault load and this fixes that. Please let me know if this solves your problem too

**Comment by NicoNekoru** [comment]
Fix landed in 1.2.4
