### ISSUE TITLE
Metabind and Dataview inline queries stop working in tables

### ISSUE THREAD

**Issue by Acenoid** [NicoNekoru/obsidan-advanced-table-xt#28]
Related to the closed issue 26 "Dataviewjs does not render" I wanted to report that the inline dataview queries stop working, as soon as I enable this plugin.

- I use the advanced tables plugin
- I use the metabind plugin , which reports "malformed table" as soon as this plugin is enabled on a note with a callout and a table inside.
- inline dataview queries like `=this.property` stop working within a table. (just a "-" for blank value is reported. Outside of tables it's fine.

Is it possible to enable the sheets plugin only for specific tables, so the plugins could co-exist until fixed?
Can the issue be resolved, or is there a workaround?

**Comment by NicoNekoru** [comment]
I am not on my computer right now so I can't test things but I rolled out a potential fix on #29

**Comment by NicoNekoru** [comment]
Should be fixed with 457107f but let me know if the issue still is occurring.

**Comment by NicoNekoru** [comment]
Fix landed in 1.2.4

**Comment by shrek-gabe-itch** [comment]
still avaliable with inline DQL
have dashes instead of values
![Screenshot 2023-11-30 001522](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/58945139/fd56f779-7e92-485c-91eb-a8d1f814bd1b)
