### ISSUE TITLE
Issues with backslash escape character and markdown links in tables

### ISSUE THREAD

**Issue by Emperyal** [NicoNekoru/obsidan-advanced-table-xt#3]
Firstly, thank you for developing this plugin. It was much needed. I've been using it and wanted to highlight a couple of issues I've encountered:

1. The backslash `\` escape character, which prevents automatic formatting of list numbers and other markdown syntaxes, does not work within tables when the plugin is active. For example:

```
| Title 1   | Title 2     | Title 3    |
|-----------|-------------|------------|
| Content 1 | Content 2   | Content 3  |
| 1\. text  | [[file name]] |          |
```

Normally, the number 1 in the above in-cell text should not be converted to a list number, but when the plugin is active, it is converted within the table. The same applies to expressions written in other markdown syntaxes. For example, when I write an expression like `\**abcdef**` using a backslash, it should stop the bold formatting and the text should appear as it is. However, this is not the case within a table; it is still converted despite the presence of a backslash.

2. I've noticed that markdown links with spaces in the filename (e.g., `[[file name with space]]`) are not functional within table cells. If there is a space in the file name, markdown links given to these files do not work within cells.

It would be great if these issues could be addressed and fixed in a future update.

![screenshot](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/46525068/a4cdb44f-cf20-40ec-af7a-ab3d0a732797)

**Comment by NicoNekoru** [comment]
Thank you for the detailed report!

> 1. The backslash `\` escape character, which prevents automatic formatting of list numbers and other markdown syntaxes, does not work within tables when the plugin is active.

Yeah I've seen this issue in my testing too and is a problem with the way the cell input is being passed to the markdown renderer. I will fix this in the next release but for now `1\\.` should do the behavior you are expecting

> 2. I've noticed that markdown links with spaces in the filename (e.g., [[file name with space]]) are not functional within table cells. If there is a space in the file name, markdown links given to these files do not work within cells.

Hmm... This seems to be another problem with the way I am parsing the markdown, `[\[file name\]]` seems to fix the issue but I will try and fix this in the next release.

**Comment by NicoNekoru** [comment]
I'm not sure if there is an elegant solution to `1.` besides just using two backslashes since the problem seems to lie in how Obsidian is handling backslashes even prior to post processing. It seems that Obsidian is already removing the initial backslash and the post processor doesn't even know that the backslash exists so AFAIK your best solution would be to use `\\`

**Comment by NicoNekoru** [comment]
`2.` Fixed in 1.0.4

**Comment by NicoNekoru** [comment]
Nevermind, I lied the error is definitely fixable. Will add to my to do list

**Comment by Emperyal** [comment]
Hi @NicoNekoru,

Thank you so much for the quick and detailed response, and for taking the time to address the issues I pointed out. Your quick fix for the markdown links with spaces is also highly appreciated. This will enhance the user experience within tables and expand the plugin's usability. Yes, you're right, using double backslashes allows for escaping, but it would be better to do this with a single backslash, as is done in Obsidian's native tables and other fields. Thank you for taking up this issue. It will make the user experience more consistent and intuitive.

**Comment by NicoNekoru** [comment]
Obisdian's native markdown tables disallow markdown that requires the start of a line (like ordered and unordered lists) so I've followed that spec. While fixing that, I found out that all backslashes seemed to not work properly in postprocessed tables which also has been fixed.
