### ISSUE TITLE
Problem with math when exported as PDF

### ISSUE THREAD

**Issue by PauloFerm** [NicoNekoru/obsidan-advanced-table-xt#30]
There is a problem with the inline (and block) math when the plugin is being used and I try to export as PDF.
I've read the #7 issue and I thing is something alike

The source
![source](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/121617023/eb213775-3801-4671-b550-2a70279f752a)

The reading view
![render](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/121617023/c405ca87-a8ee-438c-a544-b4a0aa351a32)

The PDF exported view
![export](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/121617023/b768439f-e29d-4727-b1da-ab4071deaeae)

**Comment by abiriadev** [comment]
It seems like Obsidian doesn't provide [section information](https://docs.obsidian.md/Reference/TypeScript+API/MarkdownSectionInformation/MarkdownSectionInformation) when exporting PDF.

**Comment by NicoNekoru** [comment]
Should be fixed on the current Obsidian version

**Comment by PauloFerm** [comment]
'Native table post processing' option must be disabled.
Works fine!

**Comment by sunnyayyl** [comment]
This might be a setup issue on my part, _but_
When I enable "Native table post processing" in setting, cell merging in the exported pdf works, but LaTeX is invisible. When I disable it, math shows up properly, but cell merging and `~` css stops working.
Plugin version: 1.2.10
Obsidian version: 1.6.7
Thanks for the great plugin nonetheless!

**Comment by sunnyayyl** [comment]
For example:
```markdown
| $0$ | <   | Test |
| --- | --- | ---- |
| $1$ | <   | Test |
```
With "Native table post processing" on:
![image](https://github.com/user-attachments/assets/2f74be98-8255-4c14-8110-d6d0c86a699c)
With it off:
![image](https://github.com/user-attachments/assets/d3571894-5c33-463c-a673-ba5a0a17ab3c)
Edit: (In hindsight, this isn't the best example, my apologies)
