### ISSUE TITLE
Table cannot be rendered immediately after code block

### ISSUE THREAD

**Issue by zhoulonghao520** [NicoNekoru/obsidan-advanced-table-xt#32]
![image](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/144794808/806b944f-5690-443c-935b-a5040ca50280)

![image](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/144794808/db0ddbfb-cce4-4359-9ec1-5df4a2954f6f)

Table cannot be rendered immediately after code block

**Comment by NicoNekoru** [comment]
Should not be a problem anymore
