### ISSUE TITLE
Remove table header function

### ISSUE THREAD

**Issue by ChloeKMJ** [NicoNekoru/obsidan-advanced-table-xt#39]
Hi, I need the ability to get rid of the header of the table. So, when I added the function to get rid of the header with CSS, I found a phenomenon that doesn't interact with Sheet extended.

This is CSS code which I apply to Obsidian.
(table thead th:empty{display:none!important;}

When I turn on the plug-in, CSS is not applied, and when I turn off the plug-in, CSS is applied.
![이미지 001](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/153053856/5a165186-0404-4c75-a653-97c439c996f5)
![이미지 002](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/153053856/ac2fe521-3458-4454-8abe-0dd033e0941e)

Can you add a function to remove the header of the table to the sheet extended plug-in?

**Comment by zhoulonghao520** [comment]
<img width="694" alt="image" src="https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/144794808/c4ee99d1-f1fa-4541-a780-ffca4a7f941d">
you can try Example 1 ：

```sheet

| 1   | 2   | 3   |
|  1   |  2   |   3  |

```



you can try Example 2：

```sheet


| ~{"display":"none"}   | <   | <   |
| --- | --- | --- |
|   1 |    2 |  3   |
|   1 |    2 |  3   |
```

These methods can all achieve the content you want

**Comment by ChloeKMJ** [comment]
@zhoulonghao520 

Thank you so much! After seeing your response, I really wanted Method 1 to work, but when I applied it, unfortunately Method 1 didn't apply to my Obsidian. 
But Method 2 works so well! 

I solved it thanks to you. Then have a nice day today!

**Comment by zhoulonghao520** [comment]
Example 1, it must be supported within a code block.

The version I am currently using for the software is v1.3.5

@ChloeKMJ

**Comment by ChloeKMJ** [comment]
@zhoulonghao520 

I got it! It's the first time to use code block. Thanks to much!
