### ISSUE TITLE
Disable table border

### ISSUE THREAD

**Issue by samopolacek** [NicoNekoru/obsidan-advanced-table-xt#40]
Is there a way to disable table borders using `sheet`?

```css
table {border: none;}
```

**Comment by NicoNekoru** [comment]
Yes, you can apply custom css to the table like this:
````
```sheet
{}
--- ~ { border: 'none' }
| a   | b   | c   |
| --- | --- | --- |
| 1   | 2   | 3   | 
```
````
For more information, check out the [readme](https://github.com/NicoNekoru/obsidan-advanced-table-xt/blob/master/README.md)
