### ISSUE TITLE
Cannot escape tilde(~)

### ISSUE THREAD

**Issue by NoNap** [NicoNekoru/obsidan-advanced-table-xt#41]
When I use a tilde(~) it shows up as invisible in reading view. I presume this is due to the usage of it for class names.

`group 2 ~ .class1`

Unfortunately, when I try to escape the tilde it still doesn't appear in reading view.

Source:

`| \~/example/ | of | desired | result |` 

Result
| | of | desired | result |
| - | - | - | - |

**Comment by NicoNekoru** [comment]
Can you provide an example table that isn't working? For me it seems that `\` is working for escape tilde.
<img width="459" alt="image" src="https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/66227158/e227078f-9fd0-422c-9eca-8f5a274bbee4">

**Comment by NoNap** [comment]
Sorry, lost track of time. Example table of what I tried below.

The source of the fifth row is what I wanted, but I figured I'd demonstrate the various ways the tilde can't be escaped.

![example](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/105068723/ff9ad348-c022-4207-9115-11235d39c2df)

**Comment by NicoNekoru** [comment]
Should be fixed
