### ISSUE TITLE
feature request: double headers

### ISSUE THREAD

**Issue by ksdavidc** [NicoNekoru/obsidan-advanced-table-xt#42]
Strange request: is there a way to have two or more lines considered as a header

```
| header 1 | < |
| subhead 1 | subhead 1 |
| --- | --- |
| r1 c1 | r1 c2 |
```

| header 1 | < |
| subhead 1 | subhead 1 |
| --- | --- |
| r1 c1 | r1 c2 |

This is useful for headings that have subheadings

**Comment by NicoNekoru** [comment]
This is doable with the code block notation:
````
```sheet
| header 1 | < |
| subhead 1 | subhead 1 |
| --- | --- |
| r1 c1 | r1 c2 |
```
````
 but Obsidian's native markdown rendering does not permit the notation with native tables.

**Comment by ksdavidc** [comment]
I didn't know that! Thanks very much for the kind reply!
