### ISSUE TITLE
The indentation of beginning of the first line

### ISSUE THREAD

**Issue by ChloeKMJ** [NicoNekoru/obsidan-advanced-table-xt#46]
hello. I use sheet extended very well to record my work.

I don't remember exactly if it's since this update (1.5.2), but when a table is created and rendered, the indentation is applied at the beginning of the first line.

Is there any way to remove it?
I'm always thankful.

![이미지 002](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/153053856/2b1edfcc-17e5-441f-8d4d-2a8652518811)

**Comment by NicoNekoru** [comment]
Should be fixed!
