### ISSUE TITLE
Obsidian V1.5.3 version, there is spacing displayed between the table header and table body, which affects the aesthetics.

### ISSUE THREAD

**Issue by zhoulonghao520** [NicoNekoru/obsidan-advanced-table-xt#51]
Obsidian version: V1.5.3
Plugin version: V1.2.5

Upon inspecting the HTML, I noticed that there are two empty `<tr><tr/>` tags,It seems strange and perplexing.

Is there a way to resolve this issue

![image](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/144794808/02a54254-f279-41a6-adf9-2964fe770e4b)

<img width="1800" alt="image" src="https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/144794808/b04d0046-fa8c-4214-88a7-822cf1e689fa">

Alternatively, you can consider using CSS to control the visibility.

.ClassName tr:not(:has(td)):empty {
  display: none;
}

This CSS rule hides the element to improve its visual appearance.

------------------------------------------------------------------------------------

![image](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/144794808/1ddcabe0-98c3-4b2e-a7e2-e996b2856ba0)

Although this approach can achieve a similar effect, if I want to make the table header have a different color, I would need to use styles to handle the first row separately.

**Comment by NicoNekoru** [comment]
Are you still having this problem?

**Comment by zhoulonghao520** [comment]
![image](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/144794808/60882165-5596-4e66-9c20-67fc7227bb4c)
No problem. I removed the spaces in the header and title through the code block.
