### ISSUE TITLE
Why is the “<br/>”tag ineffective in tables in version 1.2.5?

### ISSUE THREAD

**Issue by zhoulonghao520** [NicoNekoru/obsidan-advanced-table-xt#52]
![image](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/144794808/636001e9-e6cc-40b0-b8af-6833446c2588)

![image](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/144794808/4f50c79b-093e-4706-9b52-07f0438569ec)

![image](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/144794808/7851d444-6e43-4200-8d97-792677ced86c)

**Comment by NicoNekoru** [comment]
I think this bug was introduced by b8b66c2 which was used to fix an old Obsidian bug with printing and reader mode. The Obsidian bug no longer exists so the janky solution is no longer necessary - will fix
