### ISSUE TITLE
[Feature Request] enable merged cells in heading and subheadings

### ISSUE THREAD

**Issue by knorke3** [NicoNekoru/obsidan-advanced-table-xt#54]
It is currently not possible to have multiple Rows in headings, like so:
![igGrid_MultiColumnHeaders_1-3261023791](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/155426840/ca353c0f-7854-4606-939f-02e001fc76a1)

**Comment by NicoNekoru** [comment]
It is possible using code block notation, see #42
