### ISSUE TITLE
The plugin is not being updated

### ISSUE THREAD

**Issue by grodax** [NicoNekoru/obsidan-advanced-table-xt#58]
I can't update the plugin to the latest version. I click on the update button, but version 1.2.8 is still installed instead of 1.2.9. Also, the connection of cells does not work using the "<" symbol either in preview mode or in reading mode.

**Comment by VerAn1015** [comment]
+1 to this one. I also tested it in Obsidian sandbox v1.5.8
The plugin is completely unusable at the moment. Thanks.

**Comment by NicoNekoru** [comment]
@grodax @VerAn1015 The bug should be fixed now.
