### ISSUE TITLE
Merge up doesn't work through table header divider row.

### ISSUE THREAD

**Issue by CeaselessWatcher** [NicoNekoru/obsidan-advanced-table-xt#59]
I have a table in the following format:

| Header | Header for 3 columns | <    | <     | Header |
| ------- | ---------------------- | ---- | ----- | ------- |
| ^         | Text                            | Text | Text | ^          |
| Text     | Text                            | Text | Text  | Text      |
| Text     | Text                            | Text  | Text  | Text   |
| Text     | Text                            | Text  | Text  | Text   |

The merged-left header works, but the merged-up ones don't.

What makes it weird, is that elsewhere, I have a much larger and more complicated table, where everything seems to work just fine.

I suspect the header row's divider may be the source of the problem. Is it possible to make it so headers can be merged up into through the divider?

**Comment by NicoNekoru** [comment]
The inability to merge through headers is intentional. It is the equivalent of Excel or Google spreadsheets not allowing you to merge through freezed and non-freezed rows or columns. What is your use case in which you went to merge a non-header cell with a header?

**Comment by CeaselessWatcher** [comment]
The text in the first non-header row is supposed to be sub-headers for the 3 columns with the shared main header. Overall not a big problem, thank you for the information :)
