### ISSUE TITLE
Merging both horizontally and vertically doesn't work like expected

### ISSUE THREAD

**Issue by maltevm** [NicoNekoru/obsidan-advanced-table-xt#6]
Hi, first of all thanks for spending time creating and supporting this plugin!

When I attempt to merge cells both horizontally and vertically I'm not getting the expected result. I guess there are multiple ways this could be working, but I haven't been able to figure out how to make cells span multiple rows and columns at the same time in an intuitive way. Consider for instance a table like this one:

```
| Header 1   | Header 2   | Header 3   |  Header 4  |
| Small cell | Big cell spanning       | Small cell |
| Small cell | multiple rows and cells | Small cell |
| Small cell | Small cell | Small cell | Small cell |
```

I have tried multiple intuitive methods, a few examples below:

Method 1:
```
| Header 1 | Header 2 | Header 3 | Header 4 |
|:---------|:---------|:---------|:---------|
|          |          |<         |          |
|          |^         |<         |          |
|          |          |          |          |
```
![image](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/22885022/04337f2e-50fe-45a2-b6b4-68265dd64b8c)

Method 2:
```
| Header 1 | Header 2 | Header 3 | Header 4 |
|:---------|:---------|:---------|:---------|
|          |          |<         |          |
|          |^         |^         |          |
|          |          |          |          |
```
![image](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/22885022/a97a7c87-3c9f-4a5c-8c3e-8dd821fc8c58)

Method 3:
```
| Header 1 | Header 2 | Header 3 | Header 4 |
|:---------|:---------|:---------|:---------|
|          |          |<         |          |
|          |^         |          |          |
|          |          |          |          |
```
![image](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/22885022/c6450fd1-7797-44f0-a387-5140d199210b)

The succesful method I have found seems quite hacky:
```
| Header 1 | Header 2 | Header 3 | Header 4 |
|:---------|:---------|:---------|:---------|
|1         |2         |<         |3         |
|4         |^                    |5         |<  |
|6         |7         |8         |9         |
```
![image](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/22885022/8154fd5b-8739-48d7-b923-b4bbe9e985cd)

I think the algorithm could be updated to support something more intuitive :)

Cheers,
Malte

**Comment by NicoNekoru** [comment]
> Hi.
> I would aslo like to add that a way to make it more intuitive would be to use something like the formatting used by [Doxygen](https://www.doxygen.nl/manual/markdown.html#md_tables). To merge cells vertically, they use the same strategy with `^`. However,  when talking about merging them horizontally, they use `||`. See the next example: 
> ```
> | Right | Center | Left  |
> | ----: | :----: | :---- |
> | 10    | 10     | 10    |
> | 1000                 |||
> ```
> ![image](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/76615801/534c8cd7-ec78-41d9-8a02-a31dd0e42bba)
> Idk if this could create some compatibility problem with other things but it would be nice to have. 
> 

This format would be convenient and not too hard to implement but the problem is that it would not be compatible with `advanced-tables` and I would like to be fully compatible with advanced tables. Thank you for the suggestion though

**Comment by NicoNekoru** [comment]
The initial merging issue with the extra cells being shown in @maltevm's Method 1 and 2 has been fixed, but the problem with Method 3 still is not. Fix will land in next patch
