### ISSUE TITLE
HTML tables do not render in reading view, but render in live preview.

### ISSUE THREAD

**Issue by dhay3** [NicoNekoru/obsidan-advanced-table-xt#69]
### What I'm trying to do

I wanna create tables with style and lists in tables. So I've used HTML element tags to create tables, but it seems the tables only rendered in live preview, not reading view, when the plugin is on. On the contrary the native tables rendered as expected in both.

eg. 
**Snippet**
```
%% HTML table %%
<table style="border:1px solid red">
<tbody>
<tr>
<th>header01</th>
<th>header02</th>
</tr>
<tr>
<td style="border:1px solid red">cell01</td>
<td style="border:1px solid red">cell02</td>
</tr>
<tr>
<td>cell01</td>
<td>cell02</td>
</tr>
</tbody>
</table>


%% Native table %%
| header01 | header02 |
| -------- | -------- |
| cell01   | cell02   |
| cell01   | cell02   |
```

**Display in live preview when the plugin is on**

![Pasted image 20240607090748](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/62749885/e5c5869b-ee39-4549-9b26-e786585b3b8d)

**Display in reading view when the plugin is on**

![Pasted image 20240607090847](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/62749885/6d7ec8a0-f525-44eb-8b09-57820b913b90)

### Things I have tried

1. Paste the same snippet in the Obsidian sandbox vault. Both tables was rendering as expected.
2. Disable Sheets extend plugin and reload. Both tables was rendering as expected.

### Environment

```
SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.5.12
	Operating system: #1 SMP PREEMPT_DYNAMIC Mon May 27 03:56:18 UTC 2024 6.9.2-1-MANJARO
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Base theme: adapt to system
	Community theme: Things v2.1.20
	Snippets enabled: 2
	Restricted mode: off
	Plugins installed: 14
	Plugins enabled: 14
		1: Advanced Tables v0.21.0
		2: Auto Link Title v1.5.4
		3: Code Styler v1.1.7
		4: Dataview v0.5.66
		5: Emoji Toolbar v0.4.1
		6: Highlightr v1.2.2
		7: Image Inserter v0.7.0
		8: Image in Editor v2.2.6
		9: Omnisearch v1.23.0
		10: Pandoc Plugin v0.4.1
		11: Paste Mode v5.0.2
		12: Terminal v3.14.0
		13: Table Generator v1.4.1
		14: Sheets Extended v1.2.10
```

**Comment by FenFM** [comment]
Hi,

I had the same problem. I was able to "fix" it.
In the settings of Sheets Extended you need to deactivate "Native table post processing".

That also means that you have to use ```sheet{}``` stuff in order to access the fuctionality of that Add-On.


I hope that helps and that I didn't do any mistakes :3

**Comment by dhay3** [comment]
It's highly appreciate, thx.
