### ISSUE TITLE
Issues with table rendering: extra <p>s and lost html markup

### ISSUE THREAD

**Issue by voltel** [NicoNekoru/obsidan-advanced-table-xt#8]
During table conversion from markdown to html, an html `<p>` elements are inserted by the plugin inside the table cells. 
I find this unexpected and undesirable. 
Could you please consider and remove unspecified elements from the table cells? 

On a related issue. At the moment, standard table rendering allows a certain mix of markdown and html markup. This works with tables as well. For example, the following markup would be properly rendered: 
```
> Number of patients (%) | Drug 1<br>(n=130) | Drug 2<br>(n=128)
> ----|:----:|:----: 
> **Total number of TEAEs** | 593  | 591 
> <div class="tab">Study drug-related</div> | 74 (57) | 64 (50) 
```

Alas, during the plugin rendering those html elements are lost. Can this be fixed?

**Comment by NicoNekoru** [comment]
This should be fixable. The root of the problem is that I am using the markdown converter+renderer built into Obsidian's API which isn't the most ideal. I suspect this is also the cause of #7 and I will try to migrate to a different markdown parser with the same featureset

**Comment by NicoNekoru** [comment]
I didn't end up changing the markdown renderer but instead used a hacky solution of removing the `<p>`s. This problem is now resolved by disabling this in settings:
<img width="585" alt="image" src="https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/66227158/a013749f-f616-4633-bb89-0f58021cfa40">

**Comment by NicoNekoru** [comment]
nvm I didn't actually finish the whole issue - html rendering now moved to #13
